Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,16 +1,27 @@
-name: Print Text from hellome.
-
-on:
-push:
-branches:
-- main
+name: main
+on: [push]
 jobs:
-print-text:
-runs-on: ubuntu-latest
+  build:
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v2
+    
+    - name: Setup node.js
+      uses: actions/setup-node@v2
+      with:
+        node-version: '18'
+    
+    - name: install package.json
+      run: npm install
+    
+    - name: Run Test1
+      run: |
+        output=$(node dist/Test1.js)
+        exit_code=$output
 
-steps:
-- name: Checkout code
-uses: actions/checkout@v2
+        if [ $exit_code -ne 0 ]; then
+          echo "Error $exit_code"
+          exit 1
+        fi
 
-- name: Print text from file.txt
-run: cat dist/index.js
